### PR TITLE
 Added Source link, fixed double Save dialog, convert to GFM, bumped dependencies

### PR DESCRIPTION
**Pull request by xonstone**
This PR implements following changes:

- Bumps dependecies
- Fixes an annoying issue where clicking the button caused 2 Save dialogs to pop up
- Adds a source link to the bottom of the markdown
- Converts now to Github Flavoured Markdown (for tables support etc.)
- Some smaller fixes, formatting and cleanup

### CODE REVIEW

**Comment by enrico-kaack** [comment]
Hi @xonstone , thank you for your pull request! Please give me a few days to review and merge this pull request.

Best, Enrico

**Comment by gengjiawen** [comment]
Is it possible we manage dependencies using `rollup` ?

**Comment by gengjiawen** [comment]
Also this website https://artsy.github.io/blog/2020/01/13/graphql-custom-directives/ looks handle code snippet wrong. Original is better in this case.

**Comment by xonstone** [comment]
> 
> 
> Is it possible we manage dependencies using `rollup` ?

Ofcourse, but that seems like a new PR and I would opt for Webpack since there are already some [examples](https://github.com/mdn/webextensions-examples/tree/master/webpack-modules).

**Comment by gengjiawen** [comment]
Also any thought on add `jest` for test case ?

**Comment by xonstone** [comment]
> Also this website https://artsy.github.io/blog/2020/01/13/graphql-custom-directives/ looks handle code snippet wrong. Original is better in this case.

Can you define how it looks wrong. I've export the same page and it looks ok. Code snippets are formatted as code blocks.

**Comment by enrico-kaack** [comment]
Thanks @xonstone for contributing!I will release the new version in the Chrome and Firefox Addon Store. 
Sorry for taking so long to merge this PR.

**Pull request merged**
